#!/usr/env/bin sh

cd ./odin
make release-native
echo PATH=$PATH:`pwd` >> ~/.profile
export PATH=$PATH:`pwd`
cd ../ols
./build.sh
echo PATH=$PATH:`pwd` >> ~/.profile
export PATH=$PATH:`pwd`

echo Welcome to the SkyShatter Engine!
echo You may need to source ~/.profile if the odin executable is not on your path.
echo To read the docs, including the docs autogenerated from your own source code and additions to the documentation, run the docs server ('thor docs')
echo To start the engine, run 'thor dev'

echo If you're a programmer, don't forget to setup your editor for OLS (Odin Lang-Server)

echo Go make something amazing!
echo --Caleb
